# Generated by Django 2.2.8 on 2019-12-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arcontents',
            options={'verbose_name': 'AR Content'},
        ),
        migrations.AlterModelTable(
            name='arcontents',
            table='ar_contents',
        ),
    ]
